function _30_operatedescr_pak()
{
	var p = new BinPAK(4, true, false);
	p.add("Movement; Move Cursor");
	p.add("Change Camera Angle");
	p.add("Talk; Investigate");
	p.add("Run");
	p.add("Open Tablet");
	p.add("Toggle Map Display");
	p.add("Move to the Left");
	p.add("Move to the Right");
	p.add("Display Controls");
	p.add("Display Log");
	p.add("Choose");
	p.add("Choose");
	p.add("Choose; Next Message");
	p.add("Cancel; Skip Message");
	p.add("Open Tablet");
	p.add("Reaction Talk");
	p.add("Toggle Message Window");
	p.add("Autoread");
	p.add("Display Controls");
	p.add("Display Log");
	p.add("Choose; Scroll");
	p.add("Choose; Scroll");
	p.add("Choose");
	p.add("Cancel");
	p.add("Close Tablet");
	p.add("―");
	p.add("Change Page");
	p.add("Change Page");
	p.add("Display Controls");
	p.add("Display Log");
	p.add("Choose; Scroll");
	p.add("Choose; Scroll");
	p.add("Choose");
	p.add("Cancel");
	p.add("―");
	p.add("―");
	p.add("―");
	p.add("―");
	p.add("Display Controls");
	p.add("―");
	p.add("Choose");
	p.add("Choose");
	p.add("Choose; Next Message");
	p.add("Cancel; Skip Message");
	p.add("Open Tablet");
	p.add("―");
	p.add("Toggle Message Window");
	p.add("Autoread");
	p.add("Display Controls");
	p.add("Display Log");
	p.add("Move Cursor");
	p.add("Move Cursor");
	p.add("Silencer");
	p.add("Speed Up Messages");
	p.add("Open Tablet");
	p.add("Shoot Ammo; Create Ammo");
	p.add("Choose Ammo");
	p.add("Concentrate");
	p.add("Display Controls");
	p.add("―");
	p.add("―");
	p.add("―");
	p.add("Lock-on");
	p.add("―");
	p.add("Reload");
	p.add("Attack; Shoot Ammo");
	p.add("Choose Ammo");
	p.add("Fever Time");
	p.add("Display Controls");
	p.add("―");
	p.add("Move Cursor");
	p.add("Move Cursor");
	p.add("Shoot Letter");
	p.add("Fast Forward");
	p.add("―");
	p.add("Shoot Letter");
	p.add("―");
	p.add("Concentrate");
	p.add("Display Controls");
	p.add("―");
	p.add("Move Cursor");
	p.add("Left, Right: Change Page");
	p.add("Grab and Place Logic Piece");
	p.add("―");
	p.add("―");
	p.add("Start Replay");
	p.add("Choose Logic Piece");
	p.add("Choose Logic Piece");
	p.add("Display Controls");
	p.add("―");
	p.add("Down, Up: Add/Remove Medals");
	p.add("Down, Up: Add/Remove Medals");
	p.add("Pull Lever");
	p.add("Quit");
	p.add("Open Present Menu");
	p.add("押し続ける：メダル１０枚単位で操作");	// TODO: what does this mean?
	p.add("―");
	p.add("―");
	p.add("Display Controls");
	p.add("―");
	p.add("Move Cursor");
	p.add("Change Camera Angle");
	p.add("Talk; Investigate");
	p.add("Exit From Room");
	p.add("Open Tablet");
	p.add("Survey");
	p.add("Look Left");
	p.add("Look Right");
	p.add("Display Controls");
	p.add("Display Log");
	return(p);
}
