function _31_operatesysr_pak()
{
	var p = new BinPAK(4, true, false);
	p.add("・Map Display\nYou can view or hide the map with the △ button.\n\n・Run\nYou can run by holding down the " + config.getCancelButton() + " button\nwhile walking.");
	p.add("・Reaction Talk\nWhen there is purple text in the message window,\na △ button icon will appear.\nThen you can press the △ button\nto enter Reaction Talk.\nYou can choose to branch off\nto a new conversation topic with the analog pad.\n\n・Choose Present\nYou may be able to give presents to people\nduring your free time.\nYou can choose what to present to give,\nand press the △ button to give the present.\n\n・Skip Message\nYou can fast forward through messages\nby holding down the " + config.getCancelButton() + " button.\n\n・Autoread\nYou can press the R button to toggle \"autoread,\"\nwhich automatically cycles through messages.\n\n・Toggle Message Window\nYou can hide or show the message window\nwith the L button.");
	p.add("・Map\nYou can view the map and go to specific points\nthat you've been to before using the map menu.\nIt also shows where other students are right now.\n\n・Ammunition\nYou can view the ammo that you have received,\nand view their specifics by pressing the " + config.getConfirmButton() + " button.\n\n・Present\nYou can view the presents that you have received,\nand view their specifics by pressing the " + config.getConfirmButton() + " button.\nYou can hold up to 99 presents at a time.\n\n・Contacts\nYou can view the profiles and information\non each character.\nThe maximum amount of information\non a character varies.\n\n・School Rules\nYou can view the rules of the school life.\n\n・System\nYou can save or load your game, change options,\nand check the Log.");
	// TODO more controls
	p.add("・スキルセット\n自由行動で獲得した学級裁判用のスキルをセットする事ができま\nす。スキルは、スキルポイントの上限までしかセットする事はでき\nません。\n\n・スキルポイント（ＳＰ）\nスキルをセットするために必要なポイントです。スキルポイントの\n最大値（右側）のぶんだけスキルをセットする事ができます。\nスキルによって必要なスキルポイントは異なります。\nキャラクター達と親密になる事でスキルポイントを増やす事ができ\nます。");
	p.add("・発言力ゲージ\n選択肢やコトダマセレクトで間違った答えを選ぶと、ダメージを受\nけます。発言力が無くなると失敗となります。\n\n・コトダマセレクト\n学級裁判中、言弾（コトダマ）の提示を求められる事があります。\n言弾（コトダマ）を選んで△ボタンで提示できます。\n\n・人物の指名\n学級裁判中、人物の指名を求められる事があります。\n人物をアナログパッド左右で選んで○ボタンで決定します。\n\n・メッセージスキップ\n×ボタンを押し続けると、メッセージを早送りする事ができます。\n\n・オートモード\nメッセージ送りアイコンが表示されている時に、Ｒボタンを押す\nと、メッセージを自動的に送る“オートモード”に切り替える事が\nできます。オートモードを解除するには、もう一度Ｒボタンを押し\nてください。\n\n・ウインドウのＯＮ／ＯＦＦ\nメッセージ送りアイコンが表示されている時に、Ｌボタンを押す\nと、メッセージウインドウなどの表示物を消す事ができます。\n消している間は、メッセージが進行しないため、進める場合は、\nもう一度Ｌボタンを押して、メッセージウインドウを表示させて\nください。");
	p.add("・発言力ゲージ\nノンストップ議論でウィークポイントに間違った言弾（コトダマ）\nを当てるとダメージを受けます。発言力が無くなると失敗となりま\nす。\n\n・集中力ゲージ\n精神集中に必要なゲージです。\n\n・精神集中\nＲボタンを押している間、精神集中を行い、時間の流れを遅くする\n事ができます。ただし、集中力ゲージを消費し、無くなると精神集\n中はできなくなります。\n\n・議論の早送り\n×ボタンを押している間、議論のスピードをあげる事ができます。\n\n・ウィークポイント\nキャラクターの発言の中で黄色くなっている文字がウィークポイン\nトです。ウィークポイントは、ウソや矛盾などの発言の穴を示して\nいます。議論中のいずれかのウィークポイントに、正しい言弾（コ\nトダマ）を当てる事で議論をクリアする事ができます。\n\n・言弾（コトダマ）の発射\n△ボタンを押すと、装填されている言弾（コトダマ）を発射しま\nす。\n\n・言弾（コトダマ）の選択\nＬボタンを押している間、コトダマシリンダーが開き、\nアナログパッドで、装填する言弾（コトダマ）を選ぶ事ができます。\nＬボタンを離すと、言弾（コトダマ）が装填されます。\n\n・クイックセレクト\nＬボタンを押してすぐに離すと、装填されている言弾（コトダマ）\nが順送りに切り替わります。\n\n・言弾（コトダマ）の記憶\n△ボタンを押し続けると、ウィークポイントの言葉を、一時的な\n言弾（コトダマ）として装填します。記憶によって手に入れた言弾\n（コトダマ）は、１度撃ったり、変更したりすると無くなります。\n\n・サイレンサー\n○ボタンで、雑音を弾き飛ばすサイレンサーを撃つ事ができます。\nサイレンサーで雑音を撃つと、タイムリミットが回復します。\nただし、雑音以外の言葉にサイレンサーが当たるとタイムリミット\nが減ってしまいます。");
	p.add("・発言力ゲージ\nマシンガントークバトルで、相手の発言が爆発するとダメージを受\nけます。発言力が無くなると失敗となります。\n\n・集中力ゲージ\nフィーバータイムに必要なゲージです。\n\n・相手の発言\nマシンガントークバトルでは、相手が次々と言葉の爆弾を放って\nきます。一定時間経つと爆発し、発言力にダメージを受けます。\n爆発する前に破壊しなければなりません。\n\n・テンポマーカー\n現在のテンポの目安です。このテンポに合わせてボタンを入力する\n必要があります。テンポが外れると“ミス”となります。\n\n・コンボとテンポアップ\nミスをせず、ボタン入力を続けて行くことでコンボとなり、一定以\n上のコンボが続くと、曲が変化し、テンポアップします。\nしかし、何度かミスすると、逆にテンポダウンしてしまいます。\n\n・ロックオン（○ボタン）\nテンポマーカーのタイミングに合わせ、○ボタンを押すと、相手の\n発言をロックオンできます。\n\n・アタック（△ボタン）\nテンポマーカーのタイミングに合わせ、△ボタンを押すと、ロック\nオンした相手の発言を破壊し、相手にダメージを与えます。\n複数の発言をロックオンしている場合、同時に複数の発言を破壊で\nきます。この時、相手に与えるダメージが通常よりも少し大きくな\nります。\nストーリーの途中から、アタックを行うと、画面下の弾数が減って\nいくようなります。弾が無くなると、相手の発言を破壊できなくな\nるので、リロードが必要です。\n\n・リロード（□ボタン）\nテンポマーカーのタイミングに合わせ、□ボタンを押すと、\n１発ずつ弾を補給する事ができます。\nストーリーの途中からリロードが必要になります。\nアクション難易度が“シンセツ”の場合、リロードの必要はありま\nせん。\n\n・フィーバータイム（Ｒボタン）\nＲボタンを押すと、集中力ゲージを消費して、フィーバータイムを\n発動できます。フィーバータイム中は、弾が常に満タンになり、\nリロードの必要が無くなります。また、強制的にテンポを最大まで\n上げることができます。\n\n・ネガティブタイム\n相手がたまに、ネガティブタイムを発動する事があります。\nネガティブタイムが発動すると、テンポマーカーが隠れてしまい、\nタイミングがとりにくくなります。\nまた、相手の発言が爆発するまでの時間が短くなります。\nアクション難易度が“シンセツ”の場合、ネガティブタイムは発生\nしません。\n\n・トドメ\n相手の発言力を無くすと、相手が最後の発言を行ってきます。\n言弾（コトダマ）を△ボタンで撃ち、正しい場合は相手を論破し、\nクリアする事ができます。\n失敗した場合は、逆にダメージを受け、相手の発言力が少し回復\nしてしまいます。\n正しい言弾（コトダマ）をＬボタンで選択しなければならない場面\nもあります。");
	p.add("・発言力ゲージ\n閃きアナグラムで間違った文字を撃ち落とすとダメ―ジを受けま\nす。発言力が無くなると失敗となります。\n\n・集中力ゲージ\n精神集中などの特殊なアクションに必要なゲージです。\n\n・精神集中\nＲボタンを押している間、精神集中を行い、時間の流れを遅くする\n事ができます。ただし、集中力ゲージを消費し、無くなると精神集\n中はできなくなります。\n\n・文字の早送り\n×ボタンを押している間、議論のスピードをあげる事ができます。\n\n・文字を撃ち落とす\n○ボタンまたは△ボタンで、文字を撃ち落とします。\n何発か撃たないと、撃ち落とせない文字もあります。");
	p.add("・発言力ゲージ\nクライマックス推理で、事件の再現を間違った場合に、ダメージを\n受けます。発言力が無くなると失敗となります。\n\n・ページの移動\n照準を画面端に持っていくとページを移動することができます。\nまた、方向キー左、方向キー右でページ単位で移動ができます。\n\n・推理コマ\n画面下に並んでいるのが推理コマです。推理コマをコマの抜けてい\nる部分に置いていく事でマンガを完成させます。\n\n・推理コマをつかむ、置く\n○ボタンを押し続けると、推理コマをつかむ事ができます。\nつかんでいる間、アナログパッドでコマを動かせます。\n○ボタンを離すと、コマを置きます。\n\n・推理コマの選択\n画面上に表示されていない推理コマはＬボタン、Ｒボタンで\n選択する事ができます。\n\n・ヒント\nコマの抜けている部分に照準を合わせ、○ボタンを押すと、ヒント\nを見る事ができます。\n\n・再現開始\n全てのコマを置き終えると、△ボタンで事件の再現を開始します。");
	p.add("・モノモノマシーンについて\nモノクマメダルを使う事でプレゼントアイテムを入手する事ができ\nます。\n\n・メダルを入れる\n方向キー下でメダルを投入する事ができます。\n方向キー上で投入したメダルを戻します。\n△ボタンを押しながら操作すると、１０枚単位で、メダルの投入が\nできます。\n\n・レバーを回す\nメダルを１枚以上投入した状態で○ボタンを押すと、レバーを\n回し、景品がでてきます。\n\n・重複率\nメダルを多く入れれば入れるほど、所持していないプレゼント\nアイテムを入手しやすくなります。\n\n・ラッキー\nたまに、ラッキーが発生し、プレゼントアイテムをさらに入手でき\nる場合があります。");
	p.add("・Survey\nYou can find investigation targets within a room\nby pressing the △ button.\n\n・Exit Room\nYou can exit a room by pressing the " + config.getCancelButton() + " button.\n\n・Reset Camera\nYou can reset the camera angle\nby pressing the L and R buttons at the same time.");
	return(p);
}
